categories:
- service
conversations:
- - what services do you provide?
  - We provide classes in English, Matematics and Computer programming.
- - what classes do you provide
  - We provide classes in English, Matematics and Computer programming.
- - What programming langaugaes do you teach.
  - We have classes in HTML, CSS, JavaScript, Java, Python
- - what languaes do you teach?
  - We have classes in HTML, CSS, JavaScript, Java, Python
- - whats the cost?
  - I depends on the class and level you like to take.
